services:
  it-tools:
    image: corentinth/it-tools:latest@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f
    container_name: it-tools
    ports:
      - "8080:80"
    networks:
      - proxy_default
    restart: unless-stopped
    labels:
      glance.name: Tools
      glance.icon: si:coder
      glance.url: https://ittools.vanes.dev
      glance.description:
      glance.id: ittools
      glance.hide: false

networks:
  proxy_default:
    external: true