services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    ports:
      - "8080:80"
    networks:
      - proxy_default
    restart: unless-stopped
    labels:
      glance.name: Tools
      glance.icon: si:coder
      glance.url: https://ittools.vanes.dev
      glance.description:
      glance.id: ittools
      glance.hide: false

networks:
  proxy_default:
    external: true