services:
  homeassistant:
    container_name: homeassistant
    networks:
      - br0
      - proxy_default
      - default
    image: ghcr.io/home-assistant/home-assistant:2025.11@sha256:c11dd7c74039223c43079d700aa559d6dc61e8e0b38a08d651f91d1bc550cff5
    volumes:
      - /mnt/user/appdata/homeassistant:/config
      - /mnt/user/immich-photos/:/config/www/immich
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    labels:
      glance.name: homeassistant
      glance.url: http://homeassistant.local:8123
      glance.description: ""
      glance.icon: si:homeassistant
      glance.id: homeassistant
      glance.hide: "false"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:2.6.3@sha256:3baac2a3b74a9945fbbcb665b3e6e0ace5df2d49b5502e3d26b66a5454316e81
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/homeassistant/z2m:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8383:8080"
    environment:
      - TZ=Europe/Amsterdam
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      glance.parent: homeassistant
      glance.name: Zigbee2MQTT
      glance.hide: "false"

  mqtt:
    image: eclipse-mosquitto:2.0.22@sha256:fd9982f5ed92a6c2a90805601d2275f8fbd7f2d47c4cb3836f7db0bdc7a91bec
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9002:9001"
    volumes:
      - /mnt/user/appdata/homeassistant/mqtt/config:/mosquitto/config:rw
      - /mnt/user/appdata/homeassistant/mqtt/data:/mosquitto/data:rw
      - /mnt/user/appdata/homeassistant/mqtt/log:/mosquitto/log:rw
    restart: unless-stopped
    labels:
      glance.parent: homeassistant
      glance.name: MQTT
      glance.hide: "false"

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.2.3@sha256:4504d794123c3f5410cc45bbc61e4d7dbcacec1e1b0cd2e599691430c94e5849
    networks:
      - proxy_default
      - default
    volumes:
      - /mnt/user/immich-photos/:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: HFA6hce7dqg.qyc5fbt
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      TZ: Europe/Amsterdam
    restart: always
    healthcheck:
      disable: false
    labels:
      glance.parent: homeassistant
      glance.name: Immich
      glance.hide: "false"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.2.3@sha256:bf339cbb44af6c2ef25d9128e1da51b2bec0cfd524846a83e3017c21bd71ddb4
    volumes:
      - /mnt/user/appdata/immich/ml/:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always
    labels:
      glance.parent: homeassistant
      glance.name: Immich Redis
      glance.hide: "false"

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: HFA6hce7dqg.qyc5fbt
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - /mnt/user/appdata/immich/db:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    labels:
      glance.parent: homeassistant
      glance.name: Immich DB
      glance.hide: "false"

networks:
  proxy_default:
    external: true
  br0:
    external: true