services:
  adguardhome:
    image: adguard/adguardhome:v0.107.64
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    # If you switch away from host networking, you can uncomment these:
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp"
    #   - "68:68/udp"
    #   - "8083:80/tcp"
    #   - "443:443/tcp"
    #   - "443:443/udp"
    #   - "3000:3000/tcp"
    #   - "853:853/tcp"
    #   - "853:853/udp"
    #   - "784:784/udp"
    #   - "8853:8853/udp"
    #   - "5443:5443/tcp"
    #   - "5443:5443/udp"
    volumes:
      - /mnt/user/appdata/adguardhome/conf:/opt/adguardhome/conf
      - /mnt/user/appdata/adguardhome/work:/opt/adguardhome/work
    environment:
      TZ: Europe/Amsterdam
    labels:
      glance.name: "Adguard Home"
      glance.description: ""
      glance.url: "http://tower.local:8083"
      glance.icon: "si:adguard"
      glance.id: "ADGH"
      glance.hide: "false"
