services:
  newt:
    image: fosrl/newt:1.6.0@sha256:18ec2c3646d09f2dc2bc4b764cb2d625d822d5dadfaeae07c9a021ae89b564c3
    container_name: newt
    restart: unless-stopped
    environment:
      PANGOLIN_ENDPOINT: https://pangolin.vanes.dev
      NEWT_ID: $newt_id_secret
      NEWT_SECRET: $newt_secret_secret
    labels:
      glance.name: Pangolin
      glance.description:
      glance.url: https://pangolin.vanes.dev
      glance.icon: si:docker
      glance.id: pangolin
      glance.hide: "false"

  npm:
    image: jc21/nginx-proxy-manager:2.13.2@sha256:342e8cfaa072e5dcdf26030279cbcd7e993b7926cb49018f4872e8cc72e87288
    container_name: npm
    restart: unless-stopped
    ports:
      - "82:80"
      - "4043:443"
      - "81:81"
    volumes:
      - /mnt/user/appdata/npm-data:/data
      - /mnt/user/appdata/npm-letsencrypt:/etc/letsencrypt
    labels:
      glance.parent: pangolin
      glance.name: Nginx proxy manager
      glance.hide: "false"