services:
  newt:
    image: fosrl/newt:1.4.1
    container_name: newt
    restart: unless-stopped
    environment:
      PANGOLIN_ENDPOINT: https://pangolin.vanes.dev
      NEWT_ID: $newt_id
      NEWT_SECRET: $newt_secret
    labels:
      glance.name: Pangolin
      glance.description:
      glance.url: https://pangolin.vanes.dev
      glance.icon: si:docker
      glance.id: pangolin
      glance.hide: "false"

  npm:
    image: jc21/nginx-proxy-manager:2.12.6
    container_name: npm
    restart: unless-stopped
    ports:
      - "82:80"
      - "4043:443"
      - "81:81"
    volumes:
      - /mnt/user/appdata/npm-data:/data
      - /mnt/user/appdata/npm-letsencrypt:/etc/letsencrypt
    labels:
      glance.parent: pangolin
      glance.name: NPM
      glance.hide: "false"