services:
  affine:
    image: ghcr.io/toeverything/affine:0.25.3@sha256:1ca80161750a41364641073fd28e19fdb9b8101f735e1985378b15510423b841
    container_name: affine
    networks:
      - proxy_default
      - default
    ports:
      - "3010:3010"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      - /mnt/user/appdata/affine/self-host/storage:/root/.affine/storage
      - /mnt/user/appdata/affine/self-host/config:/root/.affine/config
    environment:
      REDIS_SERVER_HOST: redis
      DATABASE_URL: postgresql://affine:ECo7esFvnpNn89H4oFoyBfQABLddHWB@postgres:5432/affine
      AFFINE_INDEXER_ENABLED: "false"
    restart: unless-stopped
    labels:
      glance.name: Affine
      glance.url: https://notes.vanes.dev
      glance.description: ""
      glance.icon: si:affine
      glance.id: affine
      glance.hide: "false"

  affine_migration:
    image: ghcr.io/toeverything/affine:0.25.3@sha256:1ca80161750a41364641073fd28e19fdb9b8101f735e1985378b15510423b841
    container_name: affine_migration_job
    volumes:
      - /mnt/user/appdata/affine/self-host/storage:/root/.affine/storage
      - /mnt/user/appdata/affine/self-host/config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      REDIS_SERVER_HOST: redis
      DATABASE_URL: postgresql://affine:ECo7esFvnpNn89H4oFoyBfQABLddHWB@postgres:5432/affine
      AFFINE_INDEXER_ENABLED: "false"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis@sha256:5c7c0445ed86918cb9efb96d95a6bfc03ed2059fe2c5f02b4d74f477ffe47915
    container_name: affine_redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    labels:
      glance.parent: affine
      glance.name: Redis
      glance.hide: "false"

  postgres:
    image: pgvector/pgvector:pg16@sha256:c3c84b85691a264aa3c5b8fc1d611e67d42b0cca8596e3d3d22dc2424c12c4e2
    container_name: affine_postgres
    volumes:
      - /mnt/user/appdata/affine/self-host/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: ECo7esFvnpNn89H4oFoyBfQABLddHWB
      POSTGRES_DB: affine
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "affine", "-d", "affine"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    labels:
      glance.parent: affine
      glance.name: Postgres
      glance.hide: "false"

networks:
  proxy_default:
    external: true
