services:
  affine:
    image: ghcr.io/toeverything/affine:0.25.4@sha256:f6b5ec392082be4d820922f0e982dcea32829105103192d5a2f3d8bbc3dc82ba
    container_name: affine
    networks:
      - proxy_default
      - default
    ports:
      - "3010:3010"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      - /mnt/user/appdata/affine/self-host/storage:/root/.affine/storage
      - /mnt/user/appdata/affine/self-host/config:/root/.affine/config
    environment:
      REDIS_SERVER_HOST: redis
      DATABASE_URL: postgresql://affine:ECo7esFvnpNn89H4oFoyBfQABLddHWB@postgres:5432/affine
      AFFINE_INDEXER_ENABLED: "false"
    restart: unless-stopped
    labels:
      glance.name: Affine
      glance.url: https://notes.vanes.dev
      glance.description: ""
      glance.icon: si:affine
      glance.id: affine
      glance.hide: "false"

  affine_migration:
    image: ghcr.io/toeverything/affine:0.25.4@sha256:f6b5ec392082be4d820922f0e982dcea32829105103192d5a2f3d8bbc3dc82ba
    container_name: affine_migration_job
    volumes:
      - /mnt/user/appdata/affine/self-host/storage:/root/.affine/storage
      - /mnt/user/appdata/affine/self-host/config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      REDIS_SERVER_HOST: redis
      DATABASE_URL: postgresql://affine:ECo7esFvnpNn89H4oFoyBfQABLddHWB@postgres:5432/affine
      AFFINE_INDEXER_ENABLED: "false"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis@sha256:43355efd22490e31ca14b9d569367d05121e2be61fd8e47937563ae2a80952ae
    container_name: affine_redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    labels:
      glance.parent: affine
      glance.name: Redis
      glance.hide: "false"

  postgres:
    image: pgvector/pgvector:pg16@sha256:0a07c4114ba6d1d04effcce3385e9f5ce305eb02e56a3d35948a415a52f193ec
    container_name: affine_postgres
    volumes:
      - /mnt/user/appdata/affine/self-host/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: ECo7esFvnpNn89H4oFoyBfQABLddHWB
      POSTGRES_DB: affine
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "affine", "-d", "affine"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    labels:
      glance.parent: affine
      glance.name: Postgres
      glance.hide: "false"

networks:
  proxy_default:
    external: true
