services:
  web:
    image: ghcr.io/karakeep-app/karakeep:0.28.0@sha256:cd2348520ba25bbee64199468cd41758ab325eecd6a3a5c40cd6443a1607f9e9
    container_name: karakeep
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/karakeep/data:/data
    ports:
      - "3002:3000"
    networks:
      - proxy_default
      - default
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      NEXTAUTH_SECRET: $karakeep_auth_secret
      MEILI_MASTER_KEY: 4RLNGew2TvVhruTueZGd7MUfnyyvEb
      NEXTAUTH_URL: https://bookmarks.vanes.dev
      OPENAI_API_KEY: $openai_api_key
      DISABLE_SIGNUPS: "false"
      DISABLE_PASSWORD_AUTH: "true"
      OAUTH_WELLKNOWN_URL: https://auth.vanes.dev/.well-known/openid-configuration
      OAUTH_CLIENT_SECRET: $karakeep_oidc_secret
      OAUTH_CLIENT_ID: $karakeep_oidc_id
      OAUTH_PROVIDER_NAME: Nora ID
    labels:
      glance.name: Karakeep
      glance.icon: si:bookstack
      glance.url: https://bookmarks.vanes.dev
      glance.description: ""
      glance.id: karakeep
      glance.hide: "false"

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124@sha256:1a0046448e0bb6c275c88f86e01faf0de62b02ec8572901256ada0a8c08be23f
    container_name: chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    labels:
      glance.parent: karakeep
      glance.name: Chrome
      glance.hide: "false"

  meilisearch:
    image: getmeili/meilisearch:v1.24.0@sha256:d991eb07331e9d1f9cec7bc0f9523fd5d51aee3b223d997e0e66206361952056
    container_name: meilisearch
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: 4RLNGew2TvVhruTueZGd7MUfnyyvEb
    volumes:
      - /mnt/user/appdata/melisearch/:/meili_data
    labels:
      glance.parent: karakeep
      glance.name: Meilisearch
      glance.hide: "false"

networks:
  proxy_default:
    external: true
